### ISSUE TITLE
Parsing a stingified lowercase MiniGuid value results in a different MiniGuid than the original used to generate the string

### ISSUE THREAD

**Issue by pkrakowiak** [jasonholloway/miniguid#5]
I hope I can make this issue clear. I was testing MiniGuid in an ASP.NET MVC environment, I wanted to use it in URLs. The ActionLink helper outputs MiniGuid values in lowercase and that is how I found this issue. Of course I can output proper case manually but after seeing this I do not trust this library to provide consistent values. I expected it to fail with an exception if I provide it an all lowercase string but instead it resulted in a different MiniGuid. I wrote a very simple and dirty unit test to show it.

```
[Fact]
public void LowercaseStringDoesNotResultInDifferentMiniGuid()
{
    var originalMiniGuid = "boevpmEyuyAexKbDnZlLIpEcsL";
    var lowercaseMiniGuid = originalMiniGuid.ToLowerInvariant();
    var wrongMiniGuid = "HUKvVSKyuyGKxkHdTzRliVKIYl";
            
    Assert.Equal(originalMiniGuid, MiniGuid.Parse(originalMiniGuid));
    Assert.NotEqual<string>(wrongMiniGuid, MiniGuid.Parse(lowercaseMiniGuid));
    //Assert.Throws<InvalidOperationException>(() => MiniGuid.Parse(lowercaseMiniGuid));
}
```

Maybe some sort of a sanity test should be performed after converting a string to MiniGuid? Currently if we take a valid MiniGuid value and convert it to a lowercase string and then convert it back to MiniGuid it does not fail but returns a totally different MiniGuid value.

**Comment by jasonholloway** [comment]
Hi Pawel, thanks for raising this, and taking the time to explain it well.

The answer is though that this is by design - MiniGuid is case-sensitive (think about how this multiplies the amount of information in a string) so lower-cased characters are just as acceptable as - and differently-valued than - capitalised ones.

While this is a practical weakness in the design, the path portions of URLs are supposed to be case-sensitive too, so http middleware of various kinds can be trusted to respect the casing (otherwise it wouldn't be complying to the [W3C specs](https://www.w3.org/TR/WD-html40-970708/htmlweb.html)). Given this, and the size saving this allows in the rendered strings, it's a purposeful trade-off. [Base64 is the same](https://base64.guru/learn/base64-characters).

I was a bit surprised at first that the ActionLink helper would alter the case, but I reckon you must have [this setting](https://stackoverflow.com/a/12055932/4252688) turned on to make the paths look nicer (which is entirely reasonable of course).

If you'll allow me to deflect away from MiniGuid slightly... I'd say that the ActionLink helper is being a bit too enthusiastic in its case mangling.

**Comment by jasonholloway** [comment]
Case-sensitivity's cropped up before though (#4) and it'd be pretty easy to alter the library to just use the lower-case alphabet and numbers instead upper case characters, but that would need to be opted into somehow...

**Comment by pkrakowiak** [comment]
> I was a bit surprised at first that the ActionLink helper would alter the case, but I reckon you must have this setting turned on to make the paths look nicer (which is entirely reasonable of course).

That's exactly it! In fact we have had this in our project for years and I completely forgot about it. It has worked great until yesterday when I tried using MiniGuid.

My route template was `/foo/{id}` where `{id}` is a MiniGuid. However, in [.NET documentation](https://docs.microsoft.com/en-us/dotnet/api/System.Web.Routing.RouteCollection.LowercaseUrls?view=netframework-4.8) it says

> If a query string is included in the URL, that part of the URL is not converted to lower case.

So in my case if I just use `foo` as the route template I get `/foo?id=<MiniGuid>` and it retains the proper mixed case. Doesn't look as clean, though.

Thank you for taking the time to write that meaningful comment, you rise good points there and I accept that explanation, it all makes sense. I actually like the mixed case of MiniGuids but I don't know yet if I'm going to use it for my purposes.

While looking at this I found [a solution to that exact problem at StackOverflow](https://stackoverflow.com/questions/15387299/preserve-case-in-route-parameters-with-lowercaseurls-enabled#15455422). Leaving it here in case somebody finds it useful.
